# COGS 108 - Data Checkpoint

# Names

- Li-An Wu
- Tony Lin
- Ray Huang
- Steven Kan

<a id='research_question'></a>
# Research Question

Does the GDP or poverty rate of a country affect the death/infected/recovered rate from COVID-19?

# Dataset(s)

*Fill in your dataset information here*

(Copy this information for each dataset)
- Dataset Name:
- Link to the dataset:
- Number of observations:

1-2 sentences describing each dataset. 

If you plan to use multiple datasets, add 1-2 sentences about how you plan to combine these datasets.

Dataset Name: Coronavirus death/infected population by country:   \
Link to the dataset: https://www.worldometers.info/coronavirus/#countries  \
Number of observation: 220  
 
Dataset Name: GDP by country              
Link to the dataset: 
Number of observation: 390            


Dataset Name: GDP by country              
Link to the dataset: 
Number of observation:            


Dataset Name: GDP by country              
Link to the dataset: 
Number of observation:

# Setup

In [4]:
## YOUR CODE HERE
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
import scipy

# Data Cleaning

Describe your data cleaning steps here.

1. drop all non relevent (not needed) columns
2. look for any null value for sepcific variable among each row and replace them with 0
3. remove outliers
4.

In [67]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION
covid_death = pd.read_csv("worldometer_coronavirus.csv")
GDP_country = pd.read_csv('WEO_Data.csv', encoding = "ISO-8859-1")
poverty = pd.read_csv("csvData.csv")
john_data = pd.read_csv('02-11-2021.csv')

In [80]:
covid_death.describe(include='all')
shit = type(covid_death['Total Cases'])
shit

Country              object
Total Cases          object
New Cases            object
Total Deaths         object
New Deaths           object
Total Recovered      object
Active Cases         object
Serious/Critical     object
Tot Cases/ 1M pop    object
Deaths/1M pop        object
Total Tests          object
Tests/1M pop         object
Population           object
dtype: object

In [62]:
covid_death = covid_death.drop(columns=['New Cases', 'New Deaths', 'Active Cases', ])

In [63]:
covid_death = covid_death.replace(np.nan, 0)

,Country,Total Cases,Total Deaths,Total Recovered,Serious/Critical,Tot Cases/ 1M pop,Deaths/1M pop,Total Tests,Tests/1M pop,Population
count,222,222,222,222,222,222,222,222,222,222
unique,222,218,173,216,106,219,161,204,204,220
top,Liechtenstein,1,0,0,0,"12,129",0,0,0,0
freq,1,2,18,3,71,2,19,19,19,3

In [64]:
covid_death.head()
pd.set_option('display.max_rows', covid_death.shape[0]+1)
covid_death

,Country,Total Cases,Total Deaths,Total Recovered,Serious/Critical,Tot Cases/ 1M pop,Deaths/1M pop,Total Tests,Tests/1M pop,Population
0,World,"108,416,629","2,381,578","80,605,048","100,035","13,909",305.5,0,0,0
1,USA,"28,010,156","487,171","17,932,117","20,407","84,318","1,467","330,424,655","994,660","332,198,570"
2,India,"10,880,794","155,489","10,589,230","8,944","7,837",112,"204,789,784","147,506",1388345614
3,Brazil,"9,716,298","236,397","8,643,693","8,318","45,512","1,107","28,600,000","133,964","213,489,750"
4,Russia,"4,042,837","79,194","3,559,142","2,300","27,696",543,"106,000,000","726,161","145,973,128"
5,UK,"3,998,655","115,529","2,056,261","3,132","58,712","1,696","80,267,452","1,178,570","68,105,802"
6,France,"3,406,685","80,803","238,753","3,337","52,120","1,236","47,466,482","726,202","65,362,676"
7,Spain,"3,041,454","64,217",0,"4,432","65,036","1,373","35,782,465","765,139","46,765,968"
8,Italy,"2,683,403","92,729","2,185,655","2,126","44,422","1,535","35,384,786","585,775","60,406,838"
9,Turkey,"2,564,427","27,187","2,453,096","1,256","30,206",320,"31,159,676","367,030","84,896,711"
10,Germany,"2,321,801","64,575","2,101,000","3,736","27,657",769,"41,758,675","497,428","83,949,242"
11,Colombia,"2,179,641","56,983","2,065,209","3,482","42,558","1,113","10,716,322","209,237","51,216,160"
12,Argentina,"2,008,345","49,874","1,806,260","3,541","44,187","1,097","6,690,005","147,192","45,450,837"
13,Mexico,"1,968,566","171,234","1,528,304","4,798","15,170","1,320","5,016,163","38,656","129,765,240"
14,Poland,"1,577,036","40,424","1,330,127","1,277","41,697","1,069","9,128,691","241,366","37,820,979"
15,Iran,"1,503,753","58,809","1,285,014","3,762","17,764",695,"9,938,625","117,405","84,652,766"
16,South Africa,"1,484,900","47,382","1,377,980",546,"24,845",793,"8,605,729","143,986","59,767,678"
17,Ukraine,"1,262,867","24,174","1,106,155",177,"28,984",555,"6,447,576","147,979","43,570,894"
18,Peru,"1,212,309","43,045","1,124,236","2,047","36,457","1,294","6,767,793","203,521","33,253,561"
19,Indonesia,"1,201,859","32,656","1,004,117",0,"4,366",119,"9,933,751","36,083","275,301,041"
20,Czechia,"1,073,966","17,902","955,938","1,075","100,172","1,670","6,853,674","639,261","10,721,248"
21,Netherlands,"1,021,643","14,727",0,534,"59,542",858,"6,970,400","406,241","17,158,277"
22,Canada,"817,163","21,088","758,328",672,"21,535",556,"22,720,596","598,766","37,945,719"
23,Portugal,"781,223","15,034","652,739",846,"76,754","1,477","7,731,314","759,587","10,178,307"
24,Chile,"764,307","19,262","723,493","1,538","39,772","1,002","8,559,790","445,424","19,217,153"
25,Romania,"757,676","19,277","703,966",973,"39,549","1,006","5,685,927","296,789","19,158,116"
26,Belgium,"733,100","21,551","50,362",303,"63,086","1,855","8,778,942","755,456","11,620,726"
27,Israel,"718,746","5,304","651,522","1,002","78,145",577,"11,358,022","1,234,891","9,197,590"
28,Iraq,"639,438","13,157","604,822",259,"15,683",323,"6,151,665","150,875","40,773,246"
29,Sweden,"608,411","12,428",0,226,"60,013","1,226","5,510,486","543,545","10,138,058"
30,Pakistan,"560,363","12,218","518,164","1,743","2,507",55,"8,360,823","37,406","223,514,389"
31,Philippines,"545,300","11,495","500,654",807,"4,936",104,"8,246,989","74,650","110,475,954"
32,Switzerland,"540,727","9,739","317,600",225,"62,198","1,120","4,674,340","537,677","8,693,588"
33,Bangladesh,"539,975","8,253","486,393",0,"3,259",50,"3,822,345","23,068","165,698,028"
34,Morocco,"477,160","8,440","457,325",333,"12,834",227,"5,493,128","147,747","37,179,216"
35,Austria,"430,870","8,170","408,426",262,"47,673",904,"4,786,728","529,619","9,038,063"
36,Serbia,"417,871","4,199","31,536",129,"47,945",482,"2,753,786","315,961","8,715,576"
37,Japan,"411,751","6,774","378,024",701,"3,262",54,"7,481,377","59,265","126,236,803"
38,Hungary,"383,735","13,543","289,520",299,"39,785","1,404","3,338,289","346,110","9,645,171"
39,Saudi Arabia,"372,073","6,424","362,947",447,"10,586",183,"12,899,937","367,038","35,146,084"
40,Jordan,"343,563","4,433","324,711",154,"33,468",432,"4,159,350","405,181","10,265,403"
41,UAE,"342,974",986,"323,191",0,"34,422",99,"27,722,025","2,782,282","9,963,773"
42,Lebanon,"331,159","3,866","222,078",927,"48,653",568,"2,758,601","405,288","6,806,512"
43,Panama,"330,075","5,572","303,610",242,"75,768","1,279","1,770,793","406,482","4,356,382"
44,Slovakia,"273,904","5,733","255,300",585,"50,154","1,050","1,881,532","344,522","5,461,276"
45,Nepal,"272,557","2,054","268,796",0,"9,253",70,"2,111,649","71,685","29,457,453"
46,Belarus,"265,284","1,830","254,032",0,"28,080",194,"4,643,526","491,514","9,447,402"
47,Georgia,"264,665","3,336","256,684",0,"66,425",837,"2,406,994","604,100","3,984,430"
48,Ecuador,"262,213","15,174","220,398",476,"14,725",852,"927,261","52,072","17,807,250"
49,Malaysia,"258,306",953,"205,774",258,"7,919",29,"5,474,691","167,830","32,620,507"
50,Croatia,"237,080","5,282","229,327",91,"57,972","1,292","1,255,786","307,070","4,089,573"
51,Bolivia,"233,854","11,044","174,329",71,"19,867",938,"630,026","53,525","11,770,699"
52,Azerbaijan,"231,840","3,173","226,345",0,"22,740",311,"2,485,483","243,785","10,195,388"
53,Bulgaria,"228,044","9,561","195,682",293,"32,973","1,382","1,502,690","217,277","6,915,998"
54,Dominican Republic,"227,764","2,917","173,882",264,"20,867",267,"1,127,561","103,306","10,914,781"
55,Tunisia,"220,478","7,429","180,830",354,"18,536",625,"913,488","76,798","11,894,620"
56,Ireland,"206,801","3,846","23,364",173,"41,596",774,"3,269,078","657,541","4,971,670"
57,Denmark,"203,793","2,280","195,625",68,"35,108",393,"14,925,205","2,571,190","5,804,785"
58,Kazakhstan,"200,044","2,540","181,974",221,"10,576",134,"6,399,596","338,341","18,914,618"
59,Costa Rica,"198,756","2,710","160,462",165,"38,799",529,"617,086","120,460","5,122,727"
60,Lithuania,"189,665","3,038","172,736",128,"70,281","1,126","2,006,910","743,670","2,698,656"
61,Slovenia,"178,133","3,692","160,953",155,"85,677","1,776","851,403","409,503","2,079,115"
62,Kuwait,"175,031",985,"163,895",114,"40,617",229,"1,640,047","380,584","4,309,288"
63,Egypt,"171,993","9,857","133,707",90,"1,662",95,"1,000,000","9,660","103,514,732"
64,Greece,"168,872","6,056","150,417",281,"16,251",583,"4,602,806","442,939","10,391,512"
65,Armenia,"168,830","3,138","160,838",0,"56,909","1,058","676,431","228,011","2,966,663"
66,Moldova,"168,826","3,626","156,198",286,"41,911",900,"662,707","164,518","4,028,162"
67,Palestine,"166,200","1,918","155,362",56,"32,124",371,"1,071,752","207,152","5,173,740"
68,Guatemala,"165,532","6,023","152,210",5,"9,136",332,"839,269","46,322","18,118,278"
69,Honduras,"158,355","3,838","62,991",416,"15,834",384,"404,607","40,456","10,001,113"
70,Qatar,"156,351",254,"147,939",80,"55,684",90,"1,455,165","518,257","2,807,805"
71,Ethiopia,"144,862","2,171","127,622",239,"1,241",19,"2,026,734","17,367","116,698,689"
72,Nigeria,"143,516","1,710","118,012",10,686,8,"1,398,630","6,684","209,252,629"
73,Paraguay,"141,775","2,891","117,855",237,"19,728",402,"690,273","96,054","7,186,326"
74,Myanmar,"141,543","3,188","129,287",0,"2,591",58,"2,473,356","45,271","54,634,436"
75,Oman,"136,622","1,539","128,461",45,"26,346",297,"1,550,000","298,897","5,185,727"
76,Venezuela,"131,828","1,260","123,811",107,"4,644",44,"2,764,178","97,378","28,386,074"
77,Libya,"126,881","2,014","109,262",0,"18,313",291,"692,111","99,892","6,928,612"
78,Bosnia and Herzegovina,"125,402","4,881","104,135",0,"38,371","1,493","625,798","191,483","3,268,168"
79,Bahrain,"110,416",393,"103,251",52,"63,553",226,"2,860,384","1,646,372","1,737,386"
80,Algeria,"110,049","2,930","75,436",42,"2,482",66,0,0,"44,335,512"
81,Kenya,"102,353","1,794","84,790",31,"1,878",33,"1,228,047","22,535","54,494,209"
82,North Macedonia,"96,152","2,966","87,122",131,"46,153","1,424","479,430","230,128","2,083,321"
83,Albania,"89,776","1,517","54,362",37,"31,217",527,"393,926","136,977","2,875,854"
84,China,"89,748","4,636","84,292",12,62,3,"160,000,000","111,163","1,439,323,776"
85,Kyrgyzstan,"85,398","1,439","82,098",50,"12,959",218,"693,811","105,281","6,590,113"
86,S. Korea,"82,837","1,507","72,936",161,"1,615",29,"6,093,369","118,787","51,296,443"
87,Uzbekistan,"79,340",622,"77,780",153,"2,350",18,"1,377,915","40,807","33,766,609"
88,Latvia,"75,509","1,431","62,844",97,"40,309",764,"1,296,148","691,928","1,873,240"
89,Sri Lanka,"73,644",379,"66,984",0,"3,430",18,"1,831,420","85,307","21,468,618"
90,Ghana,"73,557",494,"66,115",113,"2,337",16,"817,990","25,993","31,469,100"
91,Zambia,"67,681",931,"61,302",372,"3,620",50,"1,004,884","53,746","18,697,026"
92,Montenegro,"67,441",869,"58,210",68,"107,370","1,384","249,215","396,767","628,115"
93,Norway,"66,070",592,"57,004",20,"12,129",109,"3,562,573","654,003","5,447,332"
94,Singapore,"59,777",29,"59,558",1,"10,168",5,"6,799,834","1,156,698","5,878,660"
95,El Salvador,"56,653","1,727","50,999",68,"8,707",265,"717,882","110,335","6,506,379"
96,Afghanistan,"55,473","2,427","48,390","1,010","1,406",62,"272,256","6,899","39,463,277"
97,Luxembourg,"52,392",604,"49,166",15,"82,870",955,"1,981,645","3,134,443","632,216"
98,Estonia,"50,993",486,"40,476",34,"38,425",366,"832,395","627,235","1,327,086"
99,Finland,"49,572",710,"40,000",18,"8,938",128,"3,038,900","547,941","5,546,035"
100,Mozambique,"48,588",514,"31,016",0,"1,529",16,"377,127","11,864","31,787,903"
101,Uruguay,"47,254",524,"41,426",81,"13,574",151,"914,413","262,675","3,481,157"
102,Uganda,"39,942",328,"14,470",0,857,7,"850,130","18,236","46,617,407"
103,Cuba,"35,772",253,"30,695",73,"3,159",22,"2,088,032","184,417","11,322,342"
104,Namibia,"35,353",382,"33,950",15,"13,761",149,"279,129","108,650","2,569,058"
105,Zimbabwe,"34,864","1,364","29,471",12,"2,325",91,"309,283","20,625","14,995,578"
106,Cyprus,"32,175",218,"2,057",35,"26,530",180,"1,411,725","1,164,050","1,212,770"
107,Cameroon,"31,394",474,"29,501",25,"1,165",18,"149,000","5,529","26,948,455"
108,Ivory Coast,"30,526",171,"28,736",0,"1,140",6,"375,487","14,023","26,776,276"
109,Senegal,"30,376",735,"24,890",56,"1,786",43,"354,085","20,813","17,012,512"
110,Australia,"28,887",909,"26,111",1,"1,125",35,"13,524,971","526,641","25,681,596"
111,Malawi,"28,270",914,"12,879",4,"1,455",47,"166,746","8,581","19,430,946"
112,Sudan,"27,820","1,849","22,208",0,626,42,0,0,"44,473,626"
113,Botswana,"24,926",202,"21,214",1,"10,470",85,"706,026","296,570","2,380,640"
114,Thailand,"24,279",80,"20,210",1,347,1,"1,217,873","17,421","69,908,085"
115,DRC,"24,152",691,"15,182",0,265,8,0,0,"91,214,579"
116,Angola,"20,261",487,"18,710",8,605,15,"178,539","5,332","33,486,722"
117,Malta,"19,497",288,"16,811",18,"44,084",651,"648,516","1,466,338","442,269"
118,Madagascar,"19,360",285,"18,490",16,688,10,"114,282","4,063","28,124,516"
119,French Polynesia,"18,257",135,"4,842",5,"64,762",479,"26,355","93,488","281,909"
120,Jamaica,"18,237",363,"12,456",18,"6,142",122,"181,173","61,019","2,969,137"
121,Maldives,"17,387",56,"15,081",178,"31,823",102,"450,943","825,344","546,370"
122,Rwanda,"17,068",231,"13,678",15,"1,298",18,"934,672","71,089","13,147,846"
123,Mauritania,"16,925",427,"16,155",23,"3,583",90,"155,532","32,923","4,724,055"
124,Eswatini,"16,396",619,"12,036",67,"14,043",530,"140,746","120,548","1,167,547"
125,French Guiana,"16,296",79,"9,995",11,"53,712",260,"138,264","455,721","303,396"
126,Guinea,"14,860",84,"14,412",24,"1,113",6,"127,079","9,519","13,349,524"
127,Syria,"14,724",968,"8,438",0,829,55,0,0,"17,759,771"
128,Cabo Verde,"14,601",138,"14,084",23,"26,087",247,"113,493","202,776","559,697"
129,Tajikistan,"13,308",90,"13,218",0,"1,376",9,0,0,"9,668,359"
130,Mayotte,"12,440",72,"2,964",28,"44,938",260,"88,733","320,536","276,827"
131,Gabon,"12,171",71,"11,275",22,"5,391",31,"469,811","208,087","2,257,757"
132,Belize,"12,114",313,"11,605",1,"30,131",779,"76,546","190,392","402,044"
133,Haiti,"12,016",246,"9,258",0,"1,046",21,"49,333","4,294","11,487,870"
134,Burkina Faso,"11,426",134,"10,279",0,538,6,0,0,"21,251,940"
135,Réunion,"10,907",47,"10,049",17,"12,129",52,"98,785","109,853","899,246"
136,Hong Kong,"10,756",192,"10,136",22,"1,428",25,"7,089,664","940,971","7,534,410"
137,Andorra,"10,391",106,"9,781",15,"134,353","1,371","193,595","2,503,135","77,341"
138,Lesotho,"9,819",212,"2,896",0,"4,561",98,"53,284","24,752","2,152,701"
139,Guadeloupe,"9,351",156,"2,242",5,"23,368",390,"124,404","310,881","400,166"
140,Suriname,"8,765",166,"8,155",8,"14,859",281,"38,781","65,746","589,865"
141,Congo,"8,354",122,"7,019",0,"1,492",22,"92,500","16,515","5,600,852"
142,Bahamas,"8,311",178,"6,931",1,"21,011",450,"63,374","160,216","395,554"
143,Mali,"8,218",340,"6,110",0,399,17,"145,929","7,082","20,605,334"
144,Guyana,"8,135",184,"7,157",7,"10,312",233,"54,043","68,505","788,892"
145,Trinidad and Tobago,"7,632",136,"7,318",2,"5,443",97,"89,062","63,512","1,402,284"
146,Aruba,"7,338",68,"6,962",11,"68,550",635,"92,611","865,151","107,046"
147,Martinique,"6,553",45,98,3,"17,471",120,"94,694","252,460","375,085"
148,Nicaragua,"6,347",171,"4,225",0,951,26,0,0,"6,672,952"
149,Iceland,"6,033",29,"5,978",0,"17,609",85,"488,851","1,426,856","342,607"
150,Djibouti,"5,966",63,"5,854",0,"5,985",63,"111,369","111,726","996,809"
151,Togo,"5,687",80,"4,789",0,677,10,"217,077","25,852","8,397,046"
152,Equatorial Guinea,"5,663",87,"5,422",1,"3,958",61,"92,894","64,919","1,430,927"
153,Somalia,"5,013",144,"3,732",0,310,9,0,0,"16,162,864"
154,CAR,"4,996",63,"4,885",2,"1,024",13,"35,523","7,278","4,881,165"
155,South Sudan,"4,960",71,"3,729",10,440,6,"95,225","8,446","11,274,320"
156,Niger,"4,665",167,"4,100",3,189,7,"76,869","3,107","24,736,683"
157,Curaçao,"4,633",22,"4,557",2,"28,163",134,"46,326","281,605","164,507"
158,Benin,"4,560",56,"3,772",0,370,5,"443,877","36,039","12,316,507"
159,Gambia,"4,302",135,"3,891",1,"1,750",55,"38,070","15,489","2,457,950"
160,Gibraltar,"4,203",83,"4,021",12,"124,774","2,464","170,144","5,051,032","33,685"
161,Channel Islands,"3,961",83,"3,534",4,"22,654",475,"339,718","1,942,922","174,849"
162,Sierra Leone,"3,813",79,"2,519",0,472,10,"116,448","14,419","8,076,095"
163,Chad,"3,581",126,"3,088",0,214,8,0,0,"16,712,347"
164,San Marino,"3,278",72,"2,956",6,"96,483","2,119","37,012","1,089,389","33,975"
165,Comoros,"3,276",122,"2,601",0,"3,719",138,0,0,"880,912"
166,Guinea-Bissau,"2,848",46,"2,432",3,"1,427",23,"47,600","23,843","1,996,362"
167,Liechtenstein,"2,537",52,"2,457",2,"66,421","1,361","26,039","681,721","38,196"
168,Eritrea,"2,429",7,"1,828",0,679,2,"23,693","6,625","3,576,527"
169,Saint Lucia,"2,415",22,"1,420",2,"13,115",119,"27,472","149,188","184,144"
170,New Zealand,"2,326",25,"2,257",0,465,5,"1,578,782","315,624","5,002,100"
171,Mongolia,"2,247",2,"1,640",3,679,0.6,"1,242,216","375,221","3,310,628"
172,Vietnam,"2,142",35,"1,529",0,22,0.4,"1,529,651","15,628","97,877,271"
173,Yemen,"2,134",616,"1,428",23,71,20,"17,404",576,"30,226,897"
174,Sint Maarten,"1,985",27,"1,869",1,"45,976",625,"16,065","372,090","43,175"
175,Liberia,"1,956",84,"1,770",2,381,16,"67,081","13,076","5,130,169"
176,Barbados,"1,904",20,"1,547",1,"6,620",70,"109,836","381,916","287,592"
177,Turks and Caicos,"1,812",12,"1,424",8,"46,416",307,"15,568","398,791","39,038"
178,Burundi,"1,771",3,773,0,146,0.2,"90,019","7,436","12,105,886"
179,Seychelles,"1,768",7,"1,215",0,"17,909",71,"5,200","52,673","98,722"
180,Monaco,"1,735",19,"1,455",7,"44,021",482,"51,953","1,318,169","39,413"
181,Sao Tome and Principe,"1,431",19,"1,094",0,"6,456",86,"11,592","52,299","221,648"
182,Saint Martin,"1,408",12,"1,050",7,"36,038",307,"18,619","476,555","39,070"
183,St. Vincent Grenadines,"1,370",6,467,2,"12,325",54,"32,118","288,943","111,157"
184,Taiwan,937,9,859,0,39,0.4,"167,278","7,016","23,843,392"
185,Papua New Guinea,914,9,846,0,101,1,"43,728","4,831","9,050,662"
186,Bhutan,863,1,855,0,"1,111",1,"496,858","639,598","776,828"
187,Bermuda,694,12,675,3,"11,169",193,"168,422","2,710,538","62,136"
188,Faeroe Islands,657,1,653,1,"13,414",20,"226,225","4,619,005","48,977"
189,Mauritius,595,10,546,0,467,8,"289,552","227,444","1,273,071"
190,Tanzania,509,21,183,7,8,0.3,0,0,"60,768,502"
191,Cambodia,479,0,463,0,28,0,"428,016","25,385","16,860,888"
192,St. Barth,455,1,247,0,"45,978",101,"15,063","1,522,130","9,896"
193,Isle of Man,436,25,407,0,"5,111",293,"29,583","346,771","85,310"
194,Cayman Islands,411,2,377,1,"6,209",30,"69,770","1,053,991","66,196"
195,Antigua and Barbuda,381,9,197,1,"3,871",91,"11,353","115,343","98,428"
196,Caribbean Netherlands,360,3,244,0,"13,650",114,"5,145","195,086","26,373"
197,Brunei,184,3,175,0,418,7,"94,954","215,778","440,055"
198,Grenada,148,1,146,0,"1,312",9,"20,288","179,788","112,844"
199,Dominica,121,0,110,0,"1,678",0,"9,977","138,385","72,096"
200,British Virgin Islands,114,1,95,0,"3,756",33,"13,223","435,612","30,355"
201,Timor-Leste,100,0,62,0,75,0,"19,919","14,934","1,333,800"
202,Fiji,56,2,54,0,62,2,"27,932","31,020","900,444"
203,Falkland Islands,53,0,38,0,"14,963",0,"6,940","1,959,345","3,542"
204,New Caledonia,52,0,49,0,181,0,"21,897","76,247","287,186"
205,Macao,48,0,46,0,73,0,"4,369","6,673","654,765"
206,Laos,45,0,41,0,6,0,"107,208","14,605","7,340,291"
207,Saint Kitts and Nevis,40,0,38,0,749,0,"8,293","155,210","53,431"
208,Greenland,30,0,30,0,528,0,"17,382","305,854","56,831"
209,Vatican City,27,0,15,0,"33,666",0,0,0,802
210,Saint Pierre Miquelon,24,0,16,0,"4,155",0,"3,729","645,602","5,776"
211,Montserrat,19,1,13,0,"3,805",200,930,"186,223","4,994"
212,Anguilla,18,0,16,0,"1,193",0,"8,256","547,299","15,085"
213,Solomon Islands,18,0,14,0,26,0,"4,500","6,455","697,149"
214,Western Sahara,10,1,8,0,16,2,0,0,"606,289"
215,MS Zaandam,9,2,7,0,0,0,0,0,0
216,Wallis and Futuna,9,0,5,0,810,0,"1,202","108,132","11,116"
217,Marshall Islands,4,0,4,0,67,0,0,0,"59,436"
218,Samoa,2,0,2,0,10,0,0,0,"199,226"
219,Micronesia,1,0,1,0,9,0,0,0,"115,764"
220,Vanuatu,1,0,1,0,3,0,470,"1,509","311,522"
221,Total:,"108,416,629","2,381,578","80,605,048","100,035","13,908.80",305.5,0,0,0

In [23]:
covid_death.shape

(224, 14)

In [44]:
GDP_country = GDP_country.drop(columns=['Subject Descriptor', 'Country/Series-specific Notes', 'Estimates Start After'])
GDP_country = GDP_country[GDP_country['Units'] == "U.S. dollars"]
pd.set_option('display.max_rows', GDP_country.shape[0]+1)
GDP_country

,Country,Units,Scale,2019,2020
0,Afghanistan,U.S. dollars,Billions,18.876,19.006
2,Albania,U.S. dollars,Billions,15.276,14.034
4,Algeria,U.S. dollars,Billions,169.267,147.323
6,Angola,U.S. dollars,Billions,89.417,62.724
8,Antigua and Barbuda,U.S. dollars,Billions,1.662,1.389
10,Argentina,U.S. dollars,Billions,444.458,382.76
12,Armenia,U.S. dollars,Billions,13.673,12.813
14,Aruba,U.S. dollars,Billions,2.888,2.288
16,Australia,U.S. dollars,Billions,"1,387.09","1,334.69"
18,Austria,U.S. dollars,Billions,446.309,432.894
20,Azerbaijan,U.S. dollars,Billions,48.048,41.666
22,The Bahamas,U.S. dollars,Billions,13.579,11.56
24,Bahrain,U.S. dollars,Billions,38.574,34.624
26,Bangladesh,U.S. dollars,Billions,302.525,317.768
28,Barbados,U.S. dollars,Billions,5.209,4.63
30,Belarus,U.S. dollars,Billions,63.085,57.708
32,Belgium,U.S. dollars,Billions,529.665,503.416
34,Belize,U.S. dollars,Billions,1.837,1.556
36,Benin,U.S. dollars,Billions,14.392,15.292
38,Bhutan,U.S. dollars,Billions,2.5,2.587
40,Bolivia,U.S. dollars,Billions,41.193,38.938
42,Bosnia and Herzegovina,U.S. dollars,Billions,19.856,18.893
44,Botswana,U.S. dollars,Billions,18.474,15.872
46,Brazil,U.S. dollars,Billions,"1,839.08","1,363.77"
48,Brunei Darussalam,U.S. dollars,Billions,13.47,10.647
50,Bulgaria,U.S. dollars,Billions,67.931,67.917
52,Burkina Faso,U.S. dollars,Billions,15.746,16.082
54,Burundi,U.S. dollars,Billions,3.111,3.131
56,Cabo Verde,U.S. dollars,Billions,1.982,1.87
58,Cambodia,U.S. dollars,Billions,26.728,26.316
60,Cameroon,U.S. dollars,Billions,38.863,39.036
62,Canada,U.S. dollars,Billions,"1,736.43","1,600.26"
64,Central African Republic,U.S. dollars,Billions,2.277,2.321
66,Chad,U.S. dollars,Billions,10.934,10.51
68,Chile,U.S. dollars,Billions,282.254,245.414
70,China,U.S. dollars,Billions,"14,401.73","14,860.78"
72,Colombia,U.S. dollars,Billions,323.561,264.933
74,Comoros,U.S. dollars,Billions,1.19,1.2
76,Democratic Republic of the Congo,U.S. dollars,Billions,49.816,46.062
78,Republic of Congo,U.S. dollars,Billions,12.542,9.964
80,Costa Rica,U.S. dollars,Billions,62.142,59.645
82,Côte d'Ivoire,U.S. dollars,Billions,58.581,61.502
84,Croatia,U.S. dollars,Billions,60.422,56.768
86,Cyprus,U.S. dollars,Billions,24.568,23.246
88,Czech Republic,U.S. dollars,Billions,250.681,241.975
90,Denmark,U.S. dollars,Billions,347.031,339.626
92,Djibouti,U.S. dollars,Billions,3.346,3.408
94,Dominica,U.S. dollars,Billions,0.588,0.545
96,Dominican Republic,U.S. dollars,Billions,89.032,77.883
98,Ecuador,U.S. dollars,Billions,107.436,93.078
100,Egypt,U.S. dollars,Billions,302.335,361.875
102,El Salvador,U.S. dollars,Billions,27.023,24.784
104,Equatorial Guinea,U.S. dollars,Billions,11.819,10.028
106,Eritrea,U.S. dollars,Billions,1.982,2.075
108,Estonia,U.S. dollars,Billions,31.475,30.468
110,Eswatini,U.S. dollars,Billions,4.587,3.848
112,Ethiopia,U.S. dollars,Billions,92.796,95.588
114,Fiji,U.S. dollars,Billions,5.407,3.932
116,Finland,U.S. dollars,Billions,269.327,267.856
118,France,U.S. dollars,Billions,"2,715.82","2,551.45"
120,Gabon,U.S. dollars,Billions,16.875,15.145
122,The Gambia,U.S. dollars,Billions,1.818,1.806
124,Georgia,U.S. dollars,Billions,17.743,16.316
126,Germany,U.S. dollars,Billions,"3,861.55","3,780.55"
128,Ghana,U.S. dollars,Billions,66.998,67.337
130,Greece,U.S. dollars,Billions,209.875,194.376
132,Grenada,U.S. dollars,Billions,1.218,1.074
134,Guatemala,U.S. dollars,Billions,76.694,76.191
136,Guinea,U.S. dollars,Billions,13.797,14.238
138,Guinea-Bissau,U.S. dollars,Billions,1.44,1.392
140,Guyana,U.S. dollars,Billions,5.174,6.806
142,Haiti,U.S. dollars,Billions,8.705,8.347
144,Honduras,U.S. dollars,Billions,24.921,23.984
146,Hong Kong SAR,U.S. dollars,Billions,365.711,341.319
148,Hungary,U.S. dollars,Billions,160.957,149.939
150,Iceland,U.S. dollars,Billions,24.224,20.805
152,India,U.S. dollars,Billions,"2,868.93","2,592.58"
154,Indonesia,U.S. dollars,Billions,"1,120.14","1,088.77"
156,Islamic Republic of Iran,U.S. dollars,Billions,583.698,610.662
158,Iraq,U.S. dollars,Billions,230.143,178.112
160,Ireland,U.S. dollars,Billions,398.469,399.064
162,Israel,U.S. dollars,Billions,394.652,383.425
164,Italy,U.S. dollars,Billions,"2,001.47","1,848.22"
166,Jamaica,U.S. dollars,Billions,15.884,14.228
168,Japan,U.S. dollars,Billions,"5,079.92","4,910.58"
170,Jordan,U.S. dollars,Billions,44.566,42.609
172,Kazakhstan,U.S. dollars,Billions,181.667,165.73
174,Kenya,U.S. dollars,Billions,95.41,101.048
176,Kiribati,U.S. dollars,Billions,0.195,0.194
178,Korea,U.S. dollars,Billions,"1,646.74","1,586.79"
180,Kosovo,U.S. dollars,Billions,7.972,7.484
182,Kuwait,U.S. dollars,Billions,135.387,108.656
184,Kyrgyz Republic,U.S. dollars,Billions,8.455,7.48
186,Lao P.D.R.,U.S. dollars,Billions,19.059,18.653
188,Latvia,U.S. dollars,Billions,34.121,33.015
190,Lebanon,U.S. dollars,Billions,52.522,18.734
192,Lesotho,U.S. dollars,Billions,2.428,1.906
194,Liberia,U.S. dollars,Billions,3.176,3.068
196,Libya,U.S. dollars,Billions,39.832,21.805
198,Lithuania,U.S. dollars,Billions,54.225,55.064
200,Luxembourg,U.S. dollars,Billions,71.113,68.613
202,Macao SAR,U.S. dollars,Billions,53.859,26.348
204,Madagascar,U.S. dollars,Billions,14.124,14.199
206,Malawi,U.S. dollars,Billions,7.663,8.33
208,Malaysia,U.S. dollars,Billions,364.684,336.33
210,Maldives,U.S. dollars,Billions,5.764,4.712
212,Mali,U.S. dollars,Billions,17.324,17.685
214,Malta,U.S. dollars,Billions,14.991,14.29
216,Marshall Islands,U.S. dollars,Billions,0.237,0.225
218,Mauritania,U.S. dollars,Billions,7.6,7.428
220,Mauritius,U.S. dollars,Billions,14.048,11.341
222,Mexico,U.S. dollars,Billions,"1,258.21","1,040.37"
224,Micronesia,U.S. dollars,Billions,0.414,0.395
226,Moldova,U.S. dollars,Billions,11.956,11.241
228,Mongolia,U.S. dollars,Billions,13.853,13.385
230,Montenegro,U.S. dollars,Billions,5.495,4.943
232,Morocco,U.S. dollars,Billions,118.567,112.22
234,Mozambique,U.S. dollars,Billions,15.195,14.557
236,Myanmar,U.S. dollars,Billions,68.641,70.89
238,Namibia,U.S. dollars,Billions,12.473,10.252
240,Nauru,U.S. dollars,Billions,0.119,0.114
242,Nepal,U.S. dollars,Billions,30.69,32.158
244,Netherlands,U.S. dollars,Billions,907.151,886.339
246,New Zealand,U.S. dollars,Billions,205.217,193.545
248,Nicaragua,U.S. dollars,Billions,12.535,11.905
250,Niger,U.S. dollars,Billions,12.912,12.971
252,Nigeria,U.S. dollars,Billions,448.12,442.976
254,North Macedonia,U.S. dollars,Billions,12.698,12.51
256,Norway,U.S. dollars,Billions,403.336,366.386
258,Oman,U.S. dollars,Billions,76.332,62.305
260,Pakistan,U.S. dollars,Billions,276.114,NaN
262,Palau,U.S. dollars,Billions,0.28,0.251
264,Panama,U.S. dollars,Billions,66.801,60.286
266,Papua New Guinea,U.S. dollars,Billions,24.809,23.283
268,Paraguay,U.S. dollars,Billions,37.433,35.606
270,Peru,U.S. dollars,Billions,230.738,195.761
272,Philippines,U.S. dollars,Billions,376.795,367.362
274,Poland,U.S. dollars,Billions,592.401,580.894
276,Portugal,U.S. dollars,Billions,237.714,221.716
278,Puerto Rico,U.S. dollars,Billions,103.262,93.968
280,Qatar,U.S. dollars,Billions,175.838,147.791
282,Romania,U.S. dollars,Billions,250.076,248.624
284,Russia,U.S. dollars,Billions,"1,702.50","1,464.08"
286,Rwanda,U.S. dollars,Billions,10.123,10.428
288,Samoa,U.S. dollars,Billions,0.851,0.829
290,San Marino,U.S. dollars,Billions,1.602,1.41
292,São Tomé and Príncipe,U.S. dollars,Billions,0.422,0.417
294,Saudi Arabia,U.S. dollars,Billions,792.967,680.897
296,Senegal,U.S. dollars,Billions,23.579,24.409
298,Serbia,U.S. dollars,Billions,51.409,51.999
300,Seychelles,U.S. dollars,Billions,1.651,1.198
302,Sierra Leone,U.S. dollars,Billions,4.213,4.14
304,Singapore,U.S. dollars,Billions,372.066,337.451
306,Slovak Republic,U.S. dollars,Billions,105.434,101.892
308,Slovenia,U.S. dollars,Billions,53.748,51.802
310,Solomon Islands,U.S. dollars,Billions,1.598,1.551
312,Somalia,U.S. dollars,Billions,4.942,4.918
314,South Africa,U.S. dollars,Billions,351.354,282.588
316,South Sudan,U.S. dollars,Billions,4.934,4.177
318,Spain,U.S. dollars,Billions,"1,394.27","1,247.46"
320,Sri Lanka,U.S. dollars,Billions,83.996,81.12
322,St. Kitts and Nevis,U.S. dollars,Billions,1.066,0.871
324,St. Lucia,U.S. dollars,Billions,2.122,1.77
326,St. Vincent and the Grenadines,U.S. dollars,Billions,0.824,0.777
328,Sudan,U.S. dollars,Billions,33.359,32.576
330,Suriname,U.S. dollars,Billions,3.697,2.538
332,Sweden,U.S. dollars,Billions,530.884,529.054
334,Switzerland,U.S. dollars,Billions,704.825,707.868
336,Syria,U.S. dollars,Billions,NaN,NaN
338,Taiwan Province of China,U.S. dollars,Billions,610.692,635.547
340,Tajikistan,U.S. dollars,Billions,8.117,7.898
342,Tanzania,U.S. dollars,Billions,60.81,64.123
344,Thailand,U.S. dollars,Billions,543.564,509.2
346,Timor-Leste,U.S. dollars,Billions,1.62,1.92
348,Togo,U.S. dollars,Billions,5.459,5.719
350,Tonga,U.S. dollars,Billions,0.517,0.503
352,Trinidad and Tobago,U.S. dollars,Billions,24.1,22.718
354,Tunisia,U.S. dollars,Billions,38.797,39.226
356,Turkey,U.S. dollars,Billions,760.94,649.436
358,Turkmenistan,U.S. dollars,Billions,45.231,47.986
360,Tuvalu,U.S. dollars,Billions,0.047,0.045
362,Uganda,U.S. dollars,Billions,36.484,37.733
364,Ukraine,U.S. dollars,Billions,154.694,142.25
366,United Arab Emirates,U.S. dollars,Billions,421.142,353.899
368,United Kingdom,U.S. dollars,Billions,"2,830.76","2,638.30"
370,United States,U.S. dollars,Billions,"21,433.23","20,807.27"
372,Uruguay,U.S. dollars,Billions,56.686,54.135
374,Uzbekistan,U.S. dollars,Billions,57.921,59.771
376,Vanuatu,U.S. dollars,Billions,0.933,0.864
378,Venezuela,U.S. dollars,Billions,63.96,48.61
380,Vietnam,U.S. dollars,Billions,329.537,340.602
382,West Bank and Gaza,U.S. dollars,Billions,17.051,14.75
384,Yemen,U.S. dollars,Billions,22.568,20.948
386,Zambia,U.S. dollars,Billions,24.156,18.909
388,Zimbabwe,U.S. dollars,Billions,18.699,14.002

In [65]:
poverty.shape

(162, 3)

In [19]:
poverty.head()

        country  povertyRate      pop2021
0  Turkmenistan          0.2     6117.924
1         China          0.6  1444216.107
2       Ukraine          1.3    43466.819
3    Kazakhstan          2.5    18994.962
4     Sri Lanka          4.1    21497.310

In [20]:
github_data.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,NaN,NaN,NaN,Afghanistan,2021-02-12 05:23:29,33.93911,67.709953,55420,2419,48279,4722.0,Afghanistan,142.364145,4.364850
1,NaN,NaN,NaN,Albania,2021-02-12 05:23:29,41.15330,20.168300,89776,1517,54362,33897.0,Albania,3119.605254,1.689761
2,NaN,NaN,NaN,Algeria,2021-02-12 05:23:29,28.03390,1.659600,110049,2930,75436,31683.0,Algeria,250.960963,2.662450
3,NaN,NaN,NaN,Andorra,2021-02-12 05:23:29,42.50630,1.521800,10391,106,9781,504.0,Andorra,13448.521323,1.020114
4,NaN,NaN,NaN,Angola,2021-02-12 05:23:29,-11.20270,17.873900,20261,487,18710,1064.0,Angola,61.646792,2.403633

# Project Proposal (updated)

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 1/20  |  1 PM | Read & Think about COGS 108 expectations; brainstorm topics/questions  | Determine best form of communication; Discuss and decide on final project topic; discuss hypothesis; begin background research | 
| 1/26  |  10 AM |  Do background research on topic | Discuss ideal dataset(s) and ethics; draft project proposal | 
| 2/1  | 10 AM  | Edit, finalize, and submit proposal; Search for datasets  | Discuss Wrangling and possible analytical approaches; Assign group members to lead each specific part   |
| 2/14  | 6 PM  | Import & Wrangle Data (Ant Man); EDA (Hulk) | Review/Edit wrangling/EDA; Discuss Analysis Plan   |
| 2/23  | 12 PM  | Finalize wrangling/EDA; Begin Analysis (Iron Man; Thor) | Discuss/edit Analysis; Complete project check-in |
| 3/13  | 12 PM  | Complete analysis; Draft results/conclusion/discussion (Wasp)| Discuss/edit full project |
| 3/19  | Before 11:59 PM  | NA | Turn in Final Project & Group Project Surveys |